name: "Check electron configuration"
permissions:
  contents: read
  pull-requests: write
  issues: write

on: 
  push:
  workflow_dispatch:
    
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '12' # Temporary version

      - uses: doyensec/electronegativity-action@0a76b0251ac45f08eaaf49fdc26c75d1951f82b6

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ../electronegativity_results
